spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/mywebdb
    username: ${DB_USER}
    password: ${DB_PASS}
  application:
    api-url: ${API_URL}
  web:
    cors:
      allowed-origins: ${BASE_API_URL}
      allowed-methods: "*"
  mail:
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

myapp:
  external-api-url: http://www.mooho.shop:8080
  external-base-api-url: http://www.mooho.shop

minio:
  endPoint: http://minio
  access-key: admin
  secret-key: 1234qwer!
  bucket: mywebbucket

FROM_ADDRESS: myWeb