spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/mywebdb
    username: ${DB_USER}
    password: ${DB_PASS}
  application:
    api-url: ${API_URL}

myapp:
  external-api-url: http://localhost:8080